### ISSUE TITLE
Different trajectory with no random function

### ISSUE THREAD

**Issue by sarrademni** [siconos/siconos#125] opened 2017-04-25 08:28 UTC
Hi
I'm working on the simulation of rock-fall trajectory, (I test a numeric simulation and compare it with  experiment). So I created 3 plans with different slopes and put 30 horizontal cubes arranged in such a way that they first impact the plan at the same time. After launching the simulation, I noticed that the cubes don't follow the same trajectory neither have the same stopping distance. 
First I thought it was because of not detecting the same contact point, but even when I changed the cubes' orientation, in such a way that they all have one only vertices in contact with the first plan, their trajectories remained different. So I wonder what is the reason of that big difference.
PS: I used a contact law with friction
Here is my code:

```
import os,sys
import numpy
import math
import pickle
from siconos.mechanics.collision.tools import Contactor
from siconos.io.mechanics_io import Hdf5
import siconos.numerics as Numerics

plan_thickness = 0.1

def normal_plane(p1,p2,p3):

  x1=p1[0]
  y1=p1[1]
  z1=p1[2]
  x2=p2[0]
  y2=p2[1]
  z2=p2[2]
  x3=p3[0]
  y3=p3[1]
  z3=p3[2]

  vector1 = [x2 - x1, y2 - y1, z2 - z1]
  vector2 = [x3 - x1, y3 - y1, z3 - z1]

  cross_product = [vector1[1] * vector2[2] - vector1[2] * vector2[1], -1 * (vector1[0] * vector2[2] - vector1[2] * vector2[0]), vector1[0] * vector2[1] - vector1[1] * vector2[0]]

  a = cross_product[0]
  b = cross_product[1]
  c = cross_product[2]
  d = - (cross_product[0] * x1 + cross_product[1] * y1 + cross_product[2] * z1)

  return numpy.array([a,b,c])/numpy.linalg.norm([a,b,c])

#create plans

# Creation of the hdf5 file 
with Hdf5(use_compression=True) as io:

  ######### amont
  v0 = numpy.array([500,161.31,107.51])
  v1 = numpy.array([-250, 161.31, 107.51])
  v2 = numpy.array([-250,93.54, 35.35])
  v3 = numpy.array([ 500, 93.54,35.35])

  amont_normal = normal_plane(v1,v2,v3)
  print('amont_normal=', amont_normal)

  v0_extruded = v0 + numpy.dot(plan_thickness,amont_normal)
  v1_extruded = v1 + numpy.dot(plan_thickness,amont_normal)
  v2_extruded = v2 + numpy.dot(plan_thickness,amont_normal)
  v3_extruded = v3 + numpy.dot(plan_thickness,amont_normal)

  amont_vertices=numpy.array([v0,v1,v2,v3,v1_extruded,v2_extruded,v3_extruded])
  print amont_vertices

  io.addConvexShape('amont',amont_vertices )
  io.addObject('amont', [Contactor('amont')],
               translation=[150, -145, -153.31])

  ######### aval
  v4 = numpy.array([-250,0,0])
  v5 = numpy.array([ 500,0,0])

  aval_normal = normal_plane(v2,v4,v3)
  print('aval_normal=', aval_normal)

  v4_extruded = v4 + numpy.dot(plan_thickness,aval_normal)
  v5_extruded = v5 + numpy.dot(plan_thickness,aval_normal)

  aval_vertices=numpy.array([v2,v3,v4,v5,v2_extruded,v3_extruded,v4_extruded,v5_extruded])
  print aval_vertices

  io.addConvexShape('aval',aval_vertices )
  io.addObject('aval', [Contactor('aval')],
               translation=[150, -145, -153.31])

  ######### sol
  v6 = numpy.array([500,-500,0])
  v7 = numpy.array([-250,-500,0])

  sol_normal = normal_plane(v4,v6,v5)
  print('sol_normal=', sol_normal)

  v6_extruded = v6 - [plan_thickness, 0.0 ,0.] + numpy.dot(plan_thickness,sol_normal)
  v7_extruded = v7 + [plan_thickness, 0.0 ,0.] + numpy.dot(plan_thickness,sol_normal)

  sol_vertices=numpy.array([v4-[plan_thickness, 0.0 ,0.],v5+[plan_thickness, 0.0 ,0.],
                                  v6-[plan_thickness, 0.0 ,0.],v7+[plan_thickness, 0.0 ,0.],
                                  v4_extruded-[plan_thickness, 0.0 ,0.],v5_extruded+[plan_thickness, 0.0 ,0.],
                                  v6_extruded,v7_extruded])
  print sol_vertices

  io.addConvexShape('sol',sol_vertices )
  io.addObject('sol', [Contactor('sol')],
               translation=[150, -145, -153.31])

  


  n_cube=1
  n_row=50
  n_col=1
  cube_size =1.44
  x_shift=3.0
  for i in range(n_row):
    for j in range(n_col):
      for n in range(n_cube):
        # Definition of a cube
        io.addConvexShape('CubeCS'+str(n)+'_'+str(i)+'_'+str(j), [ (-cube_size, cube_size, -cube_size),
                                                                   (-cube_size, -cube_size, -cube_size),
                                                                   (-cube_size, -cube_size, cube_size),
                                                                   (-cube_size, cube_size, cube_size),
                                                                   (cube_size, cube_size, cube_size),
                                                                   (cube_size, cube_size, -cube_size),
                                                                   (cube_size, -cube_size, -cube_size),
                                                                   (cube_size, -cube_size, cube_size)])


        io.addObject('cube'+str(n)+'_'+str(i)+'_'+str(j), [Contactor('CubeCS'+str(n)+'_'+str(i)+'_'+str(j))],
                     translation=[i*(5+x_shift*cube_size), x_shift*j*(5+cube_size), (5+cube_size*x_shift)*n], orientation=[1,1,1,0], 
                     velocity=[0, 0, 0, 0, 0, 0],
                     mass=6.4)


  # Definition of a non smooth law
  io.addNewtonImpactFrictionNSL('contact', e=0.01, mu=0.9)


step=1000
hstep=0.005

with Hdf5(mode='r+') as io:


  io.run(with_timer=False,
         time_stepping=None,
         space_filter=None,
         body_class=None,
         shape_class=None,
         face_class=None,
         edge_class=None,
         gravity_scale=1./100,
         t0=0,
         T=step*hstep,
         h=hstep,
         multipoints_iterations=True,
         theta=0.50001,
         Newton_max_iter=1,
         set_external_forces=None,
         solver=Numerics.SICONOS_FRICTION_3D_NSGS,
         itermax=100,
         tolerance=1e-4,
         numerics_verbose=False,
         output_frequency=10)
```

----------------------------------------------------------------------------

**Comment by vacary** [comment] 2017-04-25 10:09
Hello Sarra
Thank you for your feedback
It seems that in your example, a vertex is missing in the definition of the "amont" plane. the results was that Bullet was positioning the contact points not exactly on the plane.

I tried to fix it in this following modified code
[sarra.py.txt](https://github.com/siconos/siconos/files/954646/sarra.py.txt)

There is still some dispersion on the sliding phase and this is due to the random location of the contact by Bullet. Perhaps, @radarsat1 knows how to control it in a better way ?

**Comment by vacary** [comment] 2017-04-25 10:35
![animation](https://cloud.githubusercontent.com/assets/3368202/25381330/99cb7e9c-29b3-11e7-85a5-de6b0d93299c.gif)

**Comment by sarrademni** [comment] 2017-04-25 12:03
I tried to add the vertex but the result doesn't change. I even downloaded your code and ran it in vain. I think it may be because of the version of siconos I have on my computer

**Comment by radarsat1** [comment] 2017-04-25 14:27
I ran the script on the master version of Siconos and I get very good results:

![vview-1](https://cloud.githubusercontent.com/assets/66805/25390404/d511e914-29a9-11e7-8727-2e4d4ce88881.png)

The remaining dispersion as @vacary says is probably due to a bit of randomness in the contact points, which by definition are ill-determined because it is a plane-plane collision. (There are infinite solutions.)  We have had success using a "cube" made of spheres in the corners, which gives more deterministic contact points.

@sarrademni we should invite you to the rockfall project over on gitlab, do you have a username there? It would be a shame to repeat the efforts we have done so far from scratch.  We are trying to build a small geophysics toolkit, but the project is private so far, we can invite you.

**Comment by vacary** [comment] 2017-04-26 06:37
@sarrademni Could you give me the version that you use by executing in the directory siconos "git log -1" ?
With the code that I sent to you, what happened ? you get the same result  or it fails ?  Could you explain me a bit further ?

**Comment by sarrademni** [comment] 2017-04-26 06:54
With the command "git log -1" I obtained this:

commit 10662e4c4461e054ba8daceb0971e80079716276
Author: Stephen Sinclair <stephen.sinclair@inria.cl>
Date:   Tue Apr 11 17:35:01 2017 -0300

    [mechanics] Fix PivotJointR for initial relative orientation.

In fact your code gave me also very different trajectories

**Comment by sarrademni** [comment] 2017-04-26 06:55
@radarsat1  yes I do have a username on GitLab
Here is the link to my profile: https://gitlab.com/sarra.demni

**Comment by radarsat1** [comment] 2017-04-26 12:53
For clarity I'll highlight the changes that Vincent made:

~~~diff
--- sarra.py	2017-04-26 09:49:55.064590440 -0300
+++ vincent.py	2017-04-25 07:07:23.000000000 -0300
@@ -51,7 +51,7 @@
   v2_extruded = v2 + numpy.dot(plan_thickness,amont_normal)
   v3_extruded = v3 + numpy.dot(plan_thickness,amont_normal)
 
-  amont_vertices=numpy.array([v0,v1,v2,v3,v1_extruded,v2_extruded,v3_extruded])
+  amont_vertices=numpy.array([v0,v1,v2,v3, v0_extruded,v1_extruded,v2_extruded,v3_extruded])
   print amont_vertices
 
   io.addConvexShape('amont',amont_vertices )
@@ -150,6 +150,6 @@
          set_external_forces=None,
          solver=Numerics.SICONOS_FRICTION_3D_NSGS,
          itermax=100,
-         tolerance=1e-4,
+         tolerance=1e-8,
          numerics_verbose=False,
          output_frequency=10)
~~~

Unfortunately I can't offer any insight as I don't see what could be different between what you are doing and what we are doing, but clearly you are getting different results.  It seems you are using a recent version of Siconos.  Not sure what to say except, make sure it is well installed and you are running the version you think you are running, correct version of Python, etc.  We must start by making sure we get the same results, only then can we proceed further.

**Comment by radarsat1** [comment] 2017-04-26 12:55
By the way if it is small perhaps you can post your HDF5 file.

**Comment by sarrademni** [comment] 2017-04-26 13:12
[triplan_100_angle46.8.hdf5.tar.gz](https://github.com/siconos/siconos/files/958444/triplan_100_angle46.8.hdf5.tar.gz)
I compressed the file because it doesn't support the hdf5 file type

**Comment by radarsat1** [comment] 2017-04-26 13:44
After looking at your file, I am afraid I simply do not get the same output when I run Vincent's version, sarra.py.txt.  Perhaps we can identify what is different about your setup.  Are you using the same version of Bullet?  What version of which operating system are you using?  Myself it is Ubuntu 16.04 with a locally-installed Bullet 2.86.  I am using Python 2.7.12 but I get the same output using Python 3.5.2 (after modifying your print statements appropriately.)

Currently I am recompiling Siconos at the version you mentioned, with Bullet 2.83 that comes with Ubuntu, to check if it is different.

**Comment by radarsat1** [comment] 2017-04-26 14:22
Ok I am happy to report that when I compiled against Ubuntu 16.04's libbullet-dev package 2.83, I got the same results as you.  I am now trying to determine if the problem is that you must upgrade to a later Bullet, or if it is just the result of Bullet's "double precision" compile option, or another option.  If there is a solution without upgrading Bullet it would better, but otherwise I would recommend you install Bullet by hand and set Siconos' options to use it.  Here is my CMake options file to use a custom Bullet, in case you want to try:

~~~
set(BULLET_INCLUDE_DIR "/home/sinclairs/.local/include/bullet")
set(BULLET_COLLISION_LIBRARY "/home/sinclairs/.local/lib/libBulletCollision.so")
set(BULLET_DYNAMICS_LIBRARY "/home/sinclairs/.local/lib/libBulletDynamics.so")
set(BULLET_MATH_LIBRARY "/home/sinclairs/.local/lib/libLinearMath.so")
set(BULLET_SOFTBODY_LIBRARY "/home/sinclairs/.local/lib/libBulletSoftBody.so")
set(BULLET_USE_DOUBLE_PRECISION ON CACHE STRING "Bullet double precision" FORCE)
~~~

**Comment by radarsat1** [comment] 2017-04-26 15:03
Ok after playing around I was unable to get Bullet 2.83 to give the correct results, even if I compile with double or single precision.  However when I moved back to 2.86 everything worked very nicely with good alignment.  So it appears that an improvement since then (I would guess probably in the "contact iterations" behaviour of Bullet), is responsible for the variance.  I recommend installing Bullet from source, at least version 2.86.  You can find it here: https://github.com/bulletphysics/bullet3

You should probably uninstall the other version before proceeding, otherwise it gets confusing which headers and libraries are in use.

By the way I also recommend eventually you avoid setting the "gravity_scale" option, it may lead to confusion.

**Comment by sarrademni** [comment] 2017-04-27 07:41
I am trying to install it since yesterday but I didn't succeed. At every command it tells that the file is not existing " Aucun fichier ou dossier de ce type " even though cmake is well installed

**Comment by sarrademni** [comment] 2017-04-27 08:05
Thank you @radarsat1 but I just installed bullet 2.86 but nothing changed in the simulation

**Comment by bremond** [comment] 2017-04-27 15:31
Hello Sarra,

As Vincent said, Bullet randomize the contact point position on convex
shapes.

A workaround to avoid this randomization would be to define only point
contactors on small spheres and set multipoints_iterations=False, but as
soon as you need contact on edges this is not sufficient.

If you have only cube contactors, as it seems to be the case, maybe you
can use Bullet cube primitive and the original implementation(*) (I
checked all of this with the latest 6888176 version) by
adding at the beginning of your python script file:

import siconos.io.mechanics_io
siconos.io.mechanics_io.set_implementation('original')

Then, cf cube.py in example directory,

Where you have

io.addConvexShape('Cube', [
        (-1.0, 1.0, -1.0),
        (-1.0, -1.0, -1.0),
        (-1.0, -1.0, 1.0),
        (-1.0, 1.0, 1.0),
        (1.0, 1.0, 1.0),
        (1.0, 1.0, -1.0),
        (1.0, -1.0, -1.0),
        (1.0, -1.0, 1.0)])

You can use:

io.addPrimitiveShape('Cube', 'Box', (2, 2, 2))

With the cube primitive (and the original implementation) the contact
points are (or seems to be) always located on vertices and as there is
no random re-initialization of them on the contact face or edge as for
the convex shape this also leads to much efficient start guesses for the
friction-contact problem solver.  You can see the difference of point
location directly with the two_cubes.py example by adding the two lines
for the original implementation, and also see the differences in solver
iterations with cube.py by adding original implementation and
commenting/uncommenting the different cube shapes.

Note that a limitation with the primitive cube shape in the original
implementation was that the restitution coefficient for the Newton
impact law could not be different than 0, but I did not check, maybe
this is correct now.

(*) for @radarsat1, the two cubes in two_cubes.py behaves similarly now
with the new implementation and this indirect solution to avoid
randomization no longer works. Maybe you already talked about this, but
I am not sure...

**Comment by radarsat1** [comment] 2017-04-27 18:24
Just a correction, Bullet does not actually randomize.  Rather, it perturbs the orientation of objects to find more contact points, but this is deterministic.  However it may return different results depending on the orientations of the objects and which object is selected to be perturbed.  Since each cube has a different position this might lead to variance, but re-running the same simulation twice does not lead to different results.

In the "new" (default) interface you can control this more precisely, instead of just turning it off and on with multipoints_iterations you can actually set the number of perturbation iterations and the maximum number of points to look for per manifold.  This can be done by providing options by passing an instance of [SiconosBulletOptions](https://github.com/siconos/siconos/blob/master/mechanics/src/collision/bullet/SiconosBulletCollisionManager.hpp#L37) to the options parameter of run().  I'll have a look at what you mention regarding two_cubes.py, although I am not sure to understand completely.  Perhaps you could open a new issue.

In any case, sure, it could be worth trying the cube primitive, but this does not address the fact that we are getting different results for the same script.  I'll repeat that I was able to reproduce the problem using an older version of Bullet (2.83) and the problem went away when I linked against Bullet 2.86.  According to @sarrademni she has tried this and it did not work so I am at a loss for further explanation at the moment.

@sarrademni, when you say "I just installed bullet 2.86 and nothing changed with the simulation", what steps did you follow exactly?  Did you compile Bullet 2.86, then set the correct options in Siconos and recompile it, and ensure it linked against the expected libraries?  You can use "ldd" (or "otool -L" on Mac) against the .so / .dylib files to check what libraries they link against.  I just want to double check because for me this made quite a big difference.

**Comment by radarsat1** [comment] 2017-04-27 18:49
Forgot to mention, you can use Bullet's cube primitive also by disabling the flag USE_CONVEXHULL_FOR_BOX in SiconosBulletCollisionManager.cpp.  However lately I have not seen any differences between these cases.  (They actually use the same convex-convex collision algorithm in practice.)  To check, I tried it myself and got the same results:.

![sarra](https://cloud.githubusercontent.com/assets/66805/25499208/144c30ae-2b61-11e7-9071-3c2f5396e12b.gif)

**Comment by sarrademni** [comment] 2017-04-28 08:46
I am actually a beginner. I never worked on this before
what I really did is just install and build bullet by using these commands:

cd build3
./premake4_linux64 gmake --double
cd gmake
make

I ran cmake-gui, chose the locations and the compiler and then configure and generate

I don't know if this is exactly what I am supposed to do

**Comment by bremond** [comment] 2017-04-28 09:54
Sorry for any confusion, I didn't see all the messages before my
answer...

I must also say to Sarra that all I said is only an attempt for a quick
workaround. The 'original' implementation is meant to be fully replaced
and to disappear in the future.

my version of bullet is 2.83, the default one on ubuntu 16.04:

ii  libbulletcollision2.83.6: 2.83.6+dfsg-3     amd64

For @radarsat1, I made the two_cubes.py example before your new
implementation just to show the different behavior between primitives
and convex shapes. This relies on bullet internals and this behavior may
change with bullet version, so the example can become meaningless. But
just have a try with bullet 2.83 and set 'original' implementation. The
contact points on the primitive cube stay on vertices. Also, as the
solutions are not the same, the two cubes does not follow the same
trajectory when they slide on the ground.

The fact that the contact point stays on vertices is interesting for
situations like sliding and stacking. With this configuration (bullet
2.83, 'original' implementation), you can also try to stack many cubes
with convex shapes and then with primitive cubes and compare the number
of solver iterations : it should be far more less with the primitive
cubes.

On Sarra example, rolling is maybe more important than sliding, so this
difference may be not relevant here, but, to me, the fact that a sliding
occurs some times, with some contact points perturbations, may explains
some little differences that may remain in trajectories.

The solution with SiconosBulletOptions is interesting. Rather than a
cube sliding, it would be great to have an example of cubes stacking
where we can control and compare the contact points
perturbation. Because even if there is some little perturbations, if the
contact points remains near some fixed locations like vertices, the
guesses for the solver would be probably better than those obtained with
the full perturbation. This could be compared to cubes stacking with
contact points specified as little spheres on vertices only.

**Comment by radarsat1** [comment] 2017-04-28 14:28
@sarrademni don't worry we will figure it out ;)

actually, what system are you running on?  I have been assuming you are using Ubuntu but I am not sure.  For Bullet I use CMake directly, not premake, but here are some instructions from scratch, for Ubuntu.  For Mac, it might be a bit different but it should be possible to adapt.

~~~
sudo apt-get -y remove --purge libbullet*
sudo apt-get -y autoremove
cd ~/
git clone http://github.com/bulletphysics/bullet3
cd bullet3
git checkout 2.86.1
mkdir bld
cd bld
cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/.local -DUSE_DOUBLE_PRECISION=ON -DBUILD_SHARED_LIBS=ON
make -j6 install
cd ~/
git clone http://github.com/siconos/siconos
cd siconos
sh Build/Pipol/rc.ubuntu
sudo apt-get install -y python-vtk
mkdir bld
cd bld
cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/.local -DWITH_BULLET=ON -DBULLET_USE_DOUBLE_PRECISION=ON
grep BULLET CMakeCache.txt | grep LIBRARY:FILEPATH  # check Bullet libraries location
make -j6 install
export LD_LIBRARY_PATH=$HOME/.local/lib
export PATH=$PATH:$HOME/.local/bin
cd ~/path/to/project
python sarra.py
siconos_vview sarra.hdf5
~~~

**Comment by radarsat1** [comment] 2017-04-28 14:31
@bremond actually these are some interesting things to discuss, but let's make a new issue to talk about two_cubes.py etc ;)

**Comment by sarrademni** [comment] 2017-05-02 06:55
I'm using Ubuntu 14.04, cmake 2.8.1 and python 2.7

**Comment by radarsat1** [comment] 2017-05-08 13:18
@sarrademni did you have any luck following the instructions I gave above?

**Comment by sarrademni** [comment] 2017-05-09 06:40
I stopped in the vtk line, it says that the packet python-vtk have some unsatisfied dependencies

**Comment by sarrademni** [comment] 2017-05-09 09:54
Just an update (@vacary speaking). 

I have installed bullet 2.86 and siconos. We get the same result (a lot of dispersion) if the orientation is equal to [1,0,0,0]. 

The previous file that was working  has an orientation of [1,1,1,0] which is not unit. Siconos is not complaining !!
We have created several examples collected in the file :
[sarra_examples.zip](https://github.com/siconos/siconos/files/986204/sarra_examples.zip)

> sarra_original.py 
This implementation use 'box' as a primitive with the original implementation

**Comment by vacary** [comment] 2017-05-09 10:49
I have installed bullet 2.86 and siconos. We get the same result (a lot of dispersion) if the orientation is equal to [1,0,0,0]. With a small angle of initial rotations, the dispersion is smaller.

The previous file was working, but  has a curious orientation of [1,1,1,0] which is not unit. Siconos is not complaining !! Nevertheless, it seems sufficient to avoid the dispersion after the first impact.

The problem comes from the gauss-seidel algorithm that introduces a specific choice  in the computation of the impulses. The contact points for the contact edges/convex hull are quote good. 3 points are selected on the edge: 2 vertices and a point in the middle. The gauss--seidel algorithm distributes the contact impulses only on two vertices. With the error due to the accuracy, the rebound is not symmetric.

We have created several examples collected in the file :
[sarra_examples.zip](https://github.com/siconos/siconos/files/986204/sarra_examples.zip)

1. original implementation with box
> sarra_original.py 

This implementation use the suggestion of @bremond :  'box' as a primitive with the original implementation
> import siconos.io.mechanics_io
> siconos.io.mechanics_io.set_implementation('original')
> io.addPrimitiveShape('Cube', 'Box', (cube_size*2,cube_size*2,cube_size*2)

**Comment by vacary** [comment] 2017-05-09 14:21
I have just added the example for spheres as contactors and a correct computation of inertia 
49d039d39bd1d7d3668cb0a46b000c70e6697f5b

**Comment by radarsat1** [comment] 2017-05-09 15:16
Ok that's interesting, the computation of the impulses must be affected by center of mass though?

Regarding visualisation, I haven't experimented much with avatars but in the past I have added a Contactor to the list in a different collision group so that it can be viewed but does not collide.

**Comment by vacary** [comment] 2017-05-09 16:59
@radarsat1, yes it is but i think that in my example the center of mass is well located. Did I make a mistake ?

I added a contractor in a dummy group but it slows considerably the computation.

**Comment by radarsat1** [comment] 2017-05-09 17:18
No, probably there is no problem with the CoM, but I am trying to think of things other than the solver that could lead to such a bias.  I am surprised by the slow-down, it should not be generating different contact problems, I will take a look when I get a chance.

**Comment by radarsat1** [comment] 2017-05-09 18:19
I always assumed Siconos was normalizing input orientations, but I think it's not the case!  What happens if you try normalized with the same orientation?  e.g., [ 0.57735027,0.57735027,0.57735027,0.]

**Comment by radarsat1** [comment] 2017-05-09 21:18
Ok I see the normalization makes no difference. Indeed the contacts are not always distributed the same.  However, it seems that it is just _very_ small differences in timing (due to different starting positions) that lead to different angles of movement that adds up quickly to different trajectories.  Is it really cause for concern?  Since all computations are already double precision and very small timestep I don't see how this can be fixed without changing the contact engine.

Remember that the behaviour is always exactly the same if the rocks have the same initial conditions.  (Including initial position.)  So I am still of the opinion that it is a difference in contact parameters.  Vincent, how did you come to the conclusion that the impulses are imbalanced with respect to the center of mass?  Can you elaborate?

You can see in this video that some contacts are not generated at the same timestep on the second collision, which is what leads one of the rocks to start going left.  On the first time step, they all behave identically, so the precision of error that leads to the difference in the second rebound must be very, very minuscule.

![cubes_sphere_contactors](https://cloud.githubusercontent.com/assets/66805/25871841/2d2951a6-34df-11e7-89e3-af95778dd59b.gif)

Actually I want to experiment with [Moby](http://physsim.sourceforge.net/)'s collision detection engine, maybe this is a good chance.  Alternatively a specific engine for convex hull-with-terrain might be needed for rockfall applications that require precision.

**Comment by radarsat1** [comment] 2017-05-09 21:20
If I completely turn off multipoint iteration I get a nice image of the bias in (initial) contact normals:

![vview-1](https://cloud.githubusercontent.com/assets/66805/25873248/288442c8-34e4-11e7-9561-3751aff304b4.png)

**Comment by radarsat1** [comment] 2017-05-09 21:25
Sorry, just realized after posting the previous comment that maybe I misinterpreted.  The blue cones are facing the same direction, so contact normals are all the same, but the white arrows point differently, this is the lambda from the solver, right?  Is that what you mean by a bad distribution of the impulses?  I cannot see why it would change with position.  Could it be in the Newton-Euler relation that performs the change of coordinates, rather than in the solver?  I'll have to check the depth of penetration in these cases and see if the contact points are geometrically the same relative to the DS.

**Comment by vacary** [comment] 2018-01-16 12:40
Could we sum-up the issue ? Is there something that we want to implement or to fix ?

**Closed** 2018-01-30 11:08 UTC
