### ISSUE TITLE
some travis builds fail after success due to c-dash

### ISSUE THREAD

**Issue by radarsat1** [siconos/siconos#259] opened 2018-10-24 19:28 UTC
Some travis builds are failing with a cdash error, @bremond I thought at some point that we changed this to not be critical.  I think it would be great to decouple Travis from c-dash since we can see its progress independently anyways via [build history](https://travis-ci.org/siconos/siconos/builds).

https://travis-ci.org/siconos/siconos/jobs/445698225

```
100% tests passed, 0 tests failed out of 1175
Total Test time (real) =  64.34 sec
Submit files (using https)
   Using HTTP submit method
   Drop site:https://cdash-tripop.inrialpes.fr/submit.php?project=Siconos
   Error when uploading file: /docker-workdir/Testing/20181024-1439/Build.xml
   Error message was: The requested URL returned error: 500 Internal Server Error
   Problems when submitting via HTTP
CMake Warning at /home/travis/build/siconos/siconos/CI/machinery/CTestDriver.cmake:172 (message):
   *** submission failure *** 
make[3]: *** [CMakeFiles/ubuntu-16-04-gcc-atlas-lapack-ctest] Error 255
make[2]: *** [CMakeFiles/ubuntu-16-04-gcc-atlas-lapack-ctest.dir/all] Error 2
make[1]: *** [CMakeFiles/docker-ctest.dir/rule] Error 2
make: *** [docker-ctest] Error 2
Command '['make', 'docker-ctest']' returned non-zero exit status 2.
return code 1
```

**Comment by vacary** [comment] 2018-10-25 06:46
I am wondering if it is possible to return an exit code before submitting to cdash .

**Comment by bremond** [comment] 2018-10-25 08:18
in ec3b57c64, I splitted the build phase and the submit phase in the ctest driver. The submit phase should only throw a warning if it fails. Let's see what it gives in the next commits. If we run into trouble again, I agree with the solution of @radarsat1 to definitively remove the submit phase from travis builds.

**Comment by radarsat1** [comment] 2018-10-25 11:05
> definitively remove the submit phase from travis builds.

not necessarily remove, just make it non-fatal. (ignore error code)

**Comment by bremond** [comment] 2018-10-26 13:10
With 0ee534983, the builds are uploaded again. The second ctest_start was referring to another configure/build/test/ tag. This tag is made with the current time, I did not see it on a simple test with an HelloWorld compilation because it was the same, but for siconos they are different...
So we have now a submit phase with an ignored error code. For example:
https://travis-ci.org/siconos/siconos/jobs/446581723

Is is ok for you ?

The reasons Travis is failing now are 2 tests errors on opensuse 42.3 with sequential mumps:

The following tests FAILED:
	427 - fc3d__NSN_AC_Tol_1e-5_Max_1000_inTol_0_inMax_0_IPARAM_1_Capsules-i100-1090 (Failed)
	798 - fc3d__NSN_AC_Tol_1e-3_Max_1000_inTol_0_inMax_0_BoxesStack1-i100000-32.hdf5 (Failed)

and one test on ubuntu 16.04 with parallel mumps:
The following tests FAILED:
	424 - fc3d__NSN_AC_Tol_1e-5_Max_1000_inTol_0_inMax_0_IPARAM_1_Capsules-i100-1090 (Failed)
CMake Error at /home/travis/build/siconos/siconos/CI/machinery/CTestDriver.cmake:174 (message):
   *** test failure ***

**Comment by fperignon** [comment] 2018-11-05 13:32
> Le 25 oct. 2018 à 08:46, Vincent Acary <notifications@github.com> a écrit :
> 
> I am wondering if it is possible to return an exit code before submitting to cdash .
> 
> 


yes, it’s possible to test a return status of the different stages in ctest,
e.g. :

ctest_configure(CAPTURE_CMAKE_ERROR CONFIGURE_STATUS)

and then check this before ctest_submit

Concerning  the error 
Submit files (using https)
   Using HTTP submit method
   Drop site:https://cdash-tripop.inrialpes.fr/submit.php?project=Siconos <https://cdash-tripop.inrialpes.fr/submit.php?project=Siconos>
   Error when uploading file: /docker-workdir/Testing/20181024-1439/Build.xml
   Error message was: The requested URL returned error: 500 Internal Server Error
   Problems when submitting via HTTP
CMake Warning at /home/travis/build/siconos/siconos/CI/machinery/CTestDriver.cmake:172 (message):
   *** submission failure *** 

I have the same kind of problem when using gitlab-ci, for different jobs and in a random way

something goes wrong on cdash side, maybe when they are several submissions at the same time
for the same project? 
Or because of files too large?

**Comment by bremond** [comment] 2018-11-05 15:40
> ctest_configure(CAPTURE_CMAKE_ERROR CONFIGURE_STATUS)

I did not try this at the configure level, but only at the test level:
in CI/machinery/CTestDriver.cmake:

   ctest_test(PARALLEL_LEVEL ${NP} RETURN_VALUE TEST_RETURN_VAL)

with then

   if(NOT TEST_RETURN_VAL EQUAL 0)
       message(FATAL_ERROR " *** test failure *** ")
     endif()
   endif()

and at the submit level:

   ctest_submit(FILES ${SUBMIT_FILES} RETURN_VALUE SUBMIT_RETURN_VAL)

with 

  if(NOT SUBMIT_RETURN_VAL EQUAL 0)
    message(WARNING " *** submission failure *** ")
  endif()

the problem is that it never worked for the submit phases (a submission
failure always leads to a ctest exit error, even with the WARNING flag
in the message call, whereas a test failure does not if you replace the
FATAL_ERROR by WARNING...)

So, in 0ee5349, I skipped this ctest mistery, and it is working now with
2 stages for ctest.

In more details, from the tasks.py we have now:

targets={'.': ['docker-build', 'docker-ctest', 'docker-submit']})

docker-submit just executes ctest with SUBMIT=ON, (only the submit part
in CTestDriver) and the error exit code can be ignored at the ctest call
level.

This also provides the possibility to have ci jobs without cdash
submission (this maybe interesting to preserve our CDash server)

The remaining errors on travis are no longer submission errors, they are
only 2 tests failing when mumps sequential is on, and one failure with mumps
parrallel


Is it ok so we can close the issue ?

**Comment by bremond** [comment] 2018-11-07 09:43
It seems that everybody is ok.

**Closed by bremond** 2018-11-07 09:43 UTC
