### ISSUE TITLE
Inadequat Error Message in Cmake

### ISSUE THREAD

**Issue by roccaa** [siconos/siconos#292] opened 2019-04-10 09:02 UTC
Hello,

I have some strange error message where cmake both find the package but still ouput a message that he failed (installation still continue without problem).

my cmake is:

```
cmake -DCMAKE_INSTALL_PREFIX=~/.local/ -DPYTHON_LIBRARY=/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6.so -DPYTHON_EXECUTABLE=/usr/bin/python3.6 -DPYTHON_INCLUDE_DIRS=/usr/include/python3.6/ ../siconos-github/
```

scipy and pyhull are installed through pip3.

```
-- Found scipy: /scratch/arocca/.local/lib/python3.6/site-packages/scipy/__init__.py  
-- Old version of scipy detected. Support for 64 bits int was added in 0.14.0, forcing 32 bits int for python bindings
```

Scipy installed version is ``scipy-1.2.1``
===> Did it succeed and the message is spurious, or failed and it is indeed working in 32bits ?

```
-- Found pyhull: /scratch/arocca/.local/lib/python3.6/site-packages/pyhull/__init__.py  
-- Warning, python pyhull package not found. Some examples may not run properly. Try pip install pyhull.
```
It does not appear here

```
-- The following OPTIONAL packages have not been found:

 * MlcpSimplex
 * GamsCApi
 * SuiteSparse
 * PathFerris
 * PathVI
 * LpSolve
```

but the package is not present in the summary either ...

```
============================================ Summary ============================================
-- siconos version 4.2.0 is now ready for compilation and installation.
-- To proceed run 'make' and 'make install' and optionaly 'make test'.
-- C++ Compiler : /usr/bin/c++ 7.3.0
-- C++ flags : 
-- C Compiler : /usr/bin/cc 7.3.0
-- C flags :  -std=c99
-- Fortran Compiler : /usr/bin/gfortran 7.3.0
-- Fortran flags :  -fPIC
-- Compilation mode is : RELEASE
-- Code Sources are in : /scratch/arocca/Siconos/siconos-github
-- Blas is atlas. 
    Blas libraries : /usr/lib/x86_64-linux-gnu/libcblas.so;/usr/lib/x86_64-linux-gnu/libatlas.so;/usr/lib/x86_64-linux-gnu/libf77blas.so.
    Blas headers : cblas.h in /usr/include/x86_64-linux-gnu.
-- Lapack is atlas.
    Lapack libraries : /usr/lib/x86_64-linux-gnu/liblapack_atlas.so;/usr/lib/x86_64-linux-gnu/atlas/liblapack.so;/usr/lib/x86_64-linux-gnu/libcblas.so;/usr/lib/x86_64-linux-gnu/libatlas.so;/usr/lib/x86_64-linux-gnu/libf77blas.so.
    Lapack headers : clapack.h in /usr/include/x86_64-linux-gnu.
-- CSparse headers : externals/SuiteSparse/CSparse
-- Python interpreter is /usr/bin/python3.6
-- Python libraries are 
-- All linking libraries are : m.
-- All include directories are : /usr/include/x86_64-linux-gnu;/usr/include;/scratch/arocca/.local/lib/python3.6/site-packages/numpy/core/include.
-- The project will be installed in /scratch/arocca/.local
-- siconos python package will be installed in /scratch/arocca/.local/lib/python3.6/site-packages
-- To get more information about dependencies, config or else, 
-- check CMakeCache.txt file or re-run cmake with -DPRINT_ENV=ON.
-- =================================================================================================

```

Thank you for your answers. 
(putting my CmakeCache.txt in attached in case [CMakeCache.txt](https://github.com/siconos/siconos/files/3062941/CMakeCache.txt) )

**Comment by fperignon** [comment] 2019-04-10 13:35
Hi,



> Le 10 avr. 2019 à 11:02, roccaa <notifications@github.com> a écrit :
> 
> Hello,
> 
> I have some strange error message where cmake both find the package but still ouput a message that he failed (installation still continue without problem).
> 
> my cmake is:
> 
> cmake -DCMAKE_INSTALL_PREFIX=~/.local/ -DPYTHON_LIBRARY=/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6.so -DPYTHON_EXECUTABLE=/usr/bin/python3.6 -DPYTHON_INCLUDE_DIRS=/usr/include/python3.6/ ../siconos-github/
> scipy and pyhull are installed through pip3.
> 
> -- Found scipy: /scratch/arocca/.local/lib/python3.6/site-packages/scipy/__init__.py  
> -- Old version of scipy detected. Support for 64 bits int was added in 0.14.0, forcing 32 bits int for python bindings
> ===> Did it succeed and the message is spurious, or failed and it is indeed working in 32bits ?
> 
> -- Found pyhull: /scratch/arocca/.local/lib/python3.6/site-packages/pyhull/__init__.py  
> -- Warning, python pyhull package not found. Some examples may not run properly. Try pip install pyhull.
> It does not appear here
> 
> 


that’s just a misprinting, do not take this into account

Can you try to update your siconos repo and reconfigure your build without all the -DPYTHON… things ?

e.g. 

cmake -DCMAKE_INSTALL_PREFIX=~/.local/  ../siconos-github/


With the last commits, python3 is supposed to be properly detected 

Don’t forget to first remove everything in the build directory and tell me it works properly

**Comment by roccaa** [comment] 2019-04-10 14:29
I updated the siconos repo, and re-run cmake with

```
 cmake -DCMAKE_INSTALL_PREFIX=~/.local/ ../siconos-github/
```

it still wrongly detects scipy and pyhull.

I do not have this problem on my other machine with ubuntu 18.04 
I guess the pb comes from the method in the installation of python modules ... using pip (linked to python3)  or pip3, with/without --user, or using apt install or apt-get install (not the same installation right so maybe not the same place ?) .... do you recommend a particular way ?

**Comment by xhub** [comment] 2019-04-10 14:46
For the scipy error, thanks for saying that it is confusing. It is successful, but it can't use 64 bits ints. So it needs to only use 32 bits (and I don't remember whether it forces it for siconos, or just the bindings).

Thanks for putting your scipy version, looks like the version check is buggy :/

**Comment by fperignon** [comment] 2019-04-10 15:56
> Le 10 avr. 2019 à 16:29, roccaa <notifications@github.com> a écrit :
> 
> I updated the siconos repo, and re-run cmake with
> 
>  cmake -DCMAKE_INSTALL_PREFIX=~/.local/ ../siconos-github/
> it still wrongly detects scipy and pyhull.
> 
> 

and the rest of the python install ?
Can you try

grep -i python CMakeCache.txt in your binary dir and send us the result ? 
> I do not have this problem on my other machine with ubuntu 18.04
> 

what is your current system ?

Anyway  we don’t really need scipy in Siconos (I think ?) , only if fclib is on, so in your cas that may not be a problem



> I guess the pb comes from the method in the installation of python modules ... using pip (linked to python3) or pip3, with/without --user, or using apt install or apt-get install (not the same installation right so maybe not the same place ?) .... do you recommend a particular way ?
> 

I recommend python3, installed with apt or any other package manager
and pip for all extra packages (rather than apt install python-numpy for example).

Using python env or conda may also be a good idea. 

What’s important, I think, is  to avoid to mix different ways to manage your python modules.

**Comment by xhub** [comment] 2019-04-10 16:47
> what is your current system ? Anyway we don’t really need scipy in Siconos (I think ?) , only if fclib is on, so in your cas that may not be a problem

Scipy is needed for the sparse matrix representation. It is a hard dependency of siconos in python.

**Comment by fperignon** [comment] 2019-04-11 14:10
> Le 10 avr. 2019 à 18:47, Olivier Huber <notifications@github.com> a écrit :
> 
> what is your current system ? Anyway we don’t really need scipy in Siconos (I think ?) , only if fclib is on, so in your cas that may not be a problem
> 
> Scipy is needed for the sparse matrix representation. It is a hard dependency of siconos in python.
> 

ah ok, I had forgetten that
Anyway, this message, "Old version of scipy detected. Support for 64 bits int was added in 0.14.0, forcing 32 bits int for python bindings
"
 occurs for scipy versions less than 0.14 which dates from 2014

Alexandre, can you try:

python3
import scipy
print(spicy.__file__)
print(scipy.__version__)

just to be sure that your version is not 0.14 and that the problem is in Siconos detection of scipy ?

**Comment by xhub** [comment] 2019-04-12 07:52
I did a ```scipy_VERSION VERSION_LESS "0.14.0"``` check in cmake that doesn't do it job (1.2.1 >= 0.14.0). However, that piece of code was removed yesterday. And the requirement updated to 0.15. This should be documented in the various requirements.txt.

The warning for scipy version 0.14.0 was needed because I had servers using that version.

**Comment by fperignon** [comment] 2019-04-12 08:04
> Le 12 avr. 2019 à 09:52, Olivier Huber <notifications@github.com> a écrit :
> 
> I did a scipy_VERSION VERSION_LESS "0.14.0" check in cmake that doesn't do it job (1.2.1 >= 0.14.0)
> 

yes I fixed that yesterday

> . However, that piece of code was removed yesterday. And the requirement updated to 0.15. This should be documented in the various requirements.txt.
> 
> 

you can put  0.14 back
but it’s rather old, no ?
I’m not sure it will fit with python3 ?
Can’t you upgrade your servers to something more recent regarding scipy ?

**Comment by roccaa** [comment] 2019-04-12 08:14
@vacary gave me a bit more installation rights on my computer as this may be the source of the problem (I will try to reinstall "everything") .

Please note I have a similar error in a faulty detection of pyhull... The problem may not necessarily come from the cmake but from my installation rights/location.

In case this does not work, I will try the travis script for installation.

**Comment by fperignon** [comment] 2019-04-12 08:25
if you’re on ubuntu, you can try the process described in Dockerfile, here ;

https://gricad-gitlab.univ-grenoble-alpes.fr/nonsmooth/siconos/tree/master/ci_gitlab/dockerfiles <https://gricad-gitlab.univ-grenoble-alpes.fr/nonsmooth/siconos/tree/master/ci_gitlab/dockerfiles>

**Comment by roccaa** [comment] 2019-04-12 08:26
Ok so now it works, so either the changes from @xhub did the trick or re-installing ``pip3`` and ``cmake`` with ``apt install`` instead of ``apt-get install`` was the solution (need more sudo rights).

I reverting to a bit older commit (few days) to confirm.

**Comment by xhub** [comment] 2019-04-12 09:22
@fperignon committed a change. I just looked at my calendar code today.

**Comment by vacary** [comment] 2019-10-23 16:28
What 's up ?

**Comment by xhub** [comment] 2019-10-23 17:32
Maybe we can also close this issue

**Closed** 2019-11-24 19:02 UTC
