### ISSUE TITLE
Hacks_modify_normals_py fails

### ISSUE THREAD

**Issue by xhub** [siconos/siconos#176] opened 2017-07-25 14:39 UTC
Traceback (most recent call last):
  File "/builds/workspace/continuous3/examples/Mechanics/Hacks/modify_normals.py", line 7, in <module>
    from siconos.mechanics.collision.tools import Contactor
ImportError: No module named mechanics.collision.tools

**Comment by radarsat1** [comment] 2017-07-25 17:32
Fixed in 6265bf795df608f67d3d4d99e9b3d8b26b15a229, but this exposed a bigger problem.
First I will say that the error message reported here doesn't make sense, the script should have made it past the import Contactor line, since all mechanics Python scripts have this import.  For me, it broke at the call to makeBulletR.

But secondly, I needed to update this, since I added q1 and q2 as arguments to the BulletR() constructor, which should be taken from the ds1 and ds2 arguments to makeBulletR().  However, I tried adding the code:

```Python
q1, q2 = None, None
if ds1: q1 = ds1.q()
if ds2: q2 = ds2.q()
```

but this segfaults, because actually ds2 is a null shared_ptr in this case.  However "if ds2" is not correctly detected it, the SWIG director calls the makeBulletR with a valid object, not with None, but the object is a null pointer, so dereferencing it segfaults.  However, since it can't be compared with None or True/False, I don't know how to detect that ds2 is invalid.

I have left this check out of the script for now since ds1 is always valid and ds2 is always null, but it would be best to figure out how to fix the director to pass None when an SP is null, because I assume this affects all the Siconos binding code.

**Comment by radarsat1** [comment] 2017-07-25 19:37
I filed a SWIG bug here:
https://github.com/swig/swig/issues/1029

Closing this issue as the problem is not specific to this issue, but affects all directors, and can likely only be fixed in SWIG.

**Closed by radarsat1** 2017-07-25 19:37 UTC

**Comment by xhub** [comment] 2017-07-25 20:50
Hey for the test looking weird,  the siconos install is never updated :( So it looks pretty old. I'll look into it.

**Comment by radarsat1** [comment] 2017-07-26 14:21
Sadly it seems this is a known issue for swig.. http://www.swig.org/Doc3.0/Library.html#Library_std_shared_ptr

> Note: There is somewhat limited support for %shared_ptr and the director feature and the degrees of success varies among the different target languages. Please help to improve this support by providing patches with improvements. 

It seems to me the solution is to simply check the shared_ptr before generating the swig wrapper object, perhaps it would be a simple patch.
